# Generated by Django 3.1.1 on 2020-09-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200929_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='clean_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
