# Generated by Django 3.1.1 on 2020-10-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_clean_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hottest_deal',
            field=models.BooleanField(default=False),
        ),
    ]
