# Generated by Django 3.1.1 on 2020-11-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_hottest_deal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default-category.jpg', upload_to='categories', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='category',
            name='subtitle',
            field=models.CharField(default='default product subtile', max_length=70),
        ),
    ]
