# Generated by Django 3.1.1 on 2020-10-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='azienda.Tag'),
        ),
    ]
