# Generated by Django 3.1.1 on 2020-10-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azienda', '0002_auto_20201014_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emplyee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('fb_link', models.URLField()),
                ('ig_link', models.URLField()),
                ('tw_link', models.URLField()),
                ('image', models.ImageField(upload_to='azienda/employees')),
            ],
        ),
    ]
