# Generated by Django 3.1.1 on 2020-10-14 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azienda', '0003_emplyee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emplyee',
            new_name='Employee',
        ),
    ]
